/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donem_proje;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.security.interfaces.RSAKey;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Cıkıs extends javax.swing.JFrame {

    Database db;
    Connection connection;
    Statement statement = null;
    ArrayList arrayList = new ArrayList();

    /**
     * Creates new form Cıkıs
     */
    public Cıkıs() {
        initComponents();
        db = new Database();
        connection = (Connection) db.getConnection();
        yükle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        oda_tablo = new javax.swing.JTable();
        oda_alani = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        hesap = new javax.swing.JTextField();
        CikisYap = new javax.swing.JButton();
        GeriGel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oda_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Oda_NO", "Oda_Turu", "Kalan"
            }
        ));
        jScrollPane1.setViewportView(oda_tablo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, 634, 356));

        oda_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        oda_alani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        oda_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda_alaniActionPerformed(evt);
            }
        });
        getContentPane().add(oda_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 100, 35));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setText("Bakiye = ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 90, 40));

        hesap.setEditable(false);
        hesap.setBackground(new Color(0,0,0,0));
        hesap.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        hesap.setBorder(null);
        hesap.setOpaque(false);
        hesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapActionPerformed(evt);
            }
        });
        getContentPane().add(hesap, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 110, 40));

        CikisYap.setBackground(new java.awt.Color(255, 153, 153));
        CikisYap.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        CikisYap.setText("CıkısYap");
        CikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisYapActionPerformed(evt);
            }
        });
        getContentPane().add(CikisYap, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 35));

        GeriGel.setBackground(new java.awt.Color(255, 153, 153));
        GeriGel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        GeriGel.setText("BACK");
        GeriGel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriGelActionPerformed(evt);
            }
        });
        getContentPane().add(GeriGel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapActionPerformed

    }//GEN-LAST:event_hesapActionPerformed

    private void CikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisYapActionPerformed
        try {

            int odaNo = Integer.parseInt(oda_alani.getSelectedItem().toString());
            String query = "SELECT * FROM musteriler WHERE oda_no =" + odaNo;

            statement = (Statement) connection.createStatement();
            statement.executeQuery(query);
            ResultSet rs = statement.executeQuery(query);
            while (rs.next()) {
                String query1 = "Update odalar Set kalanlar = NULL where oda_no=" + odaNo;
                String query2 = "Delete from musteriler where oda_no=" + odaNo;
                System.out.println(query1);

                sil(query2, query1);
                Musteri musteri = new Musteri(rs.getInt("bakiye"));
                int bakiye = musteri.getBakiye();
                hesap.setText(Integer.toString(bakiye));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Cıkıs.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel tablo = (DefaultTableModel) oda_tablo.getModel();
        for (int i = 0; i < 10; i++) {
            tablo.removeRow(0);
        }
        yükle();
    }//GEN-LAST:event_CikisYapActionPerformed
    public void sil(String query1, String query2) {
        try {
            statement = (Statement) connection.createStatement();

            statement.executeUpdate(query1);
            statement.executeUpdate(query2);
        } catch (SQLException ex) {
            Logger.getLogger(MusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void oda_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oda_alaniActionPerformed

    private void GeriGelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriGelActionPerformed
        OtelTest otelTest = new OtelTest();
        otelTest.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GeriGelActionPerformed

    public void yükle() {
        DefaultTableModel tablo = (DefaultTableModel) oda_tablo.getModel();
        try {
            String query = "SELECT * FROM odalar";
            statement = (Statement) connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            System.out.println(query);

            while (rs.next()) {
                Oda oda = new Oda(rs.getInt("oda_no"), rs.getString("oda_turu"), rs.getString("kalanlar"));
                //System.out.println(oda);
                tablo.addRow(new Object[]{oda.getOda_no(), oda.getOda_turu(), oda.getKalanlar()});
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Cıkıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CikisYap;
    private javax.swing.JButton GeriGel;
    private javax.swing.JTextField hesap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> oda_alani;
    private javax.swing.JTable oda_tablo;
    // End of variables declaration//GEN-END:variables
}
