/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donem_proje;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import static java.awt.Event.INSERT;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.DropMode.INSERT;

/**
 *
 * @author User
 */
public class MusteriEkle extends javax.swing.JFrame {
Database db;
    Connection connection;
    Statement statement = null;
    ArrayList arrayList = new ArrayList();
    ArrayList<String> bos_odalar;
    public MusteriEkle(ArrayList bos_odalar) {
        initComponents();
        db = new Database();
        connection = (Connection) db.getConnection();
        this.bos_odalar = bos_odalar;
        odalari_yukle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        isim_alani = new javax.swing.JTextField();
        soyisim_alani = new javax.swing.JTextField();
        telno_alani = new javax.swing.JTextField();
        tc_alani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GeriGel = new javax.swing.JButton();
        Ekle = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        yas_alani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hata = new javax.swing.JLabel();
        gun_alani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        oda_alani = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setText("İsim");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, 70, 30));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setText("Soyisim : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, 30));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setText("Tc");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, 30));

        isim_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        isim_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isim_alaniActionPerformed(evt);
            }
        });
        getContentPane().add(isim_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 30));

        soyisim_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(soyisim_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 30));

        telno_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        telno_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telno_alaniActionPerformed(evt);
            }
        });
        getContentPane().add(telno_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 30));

        tc_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(tc_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, 30));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setText("TelNo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, 30));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel5.setText("Müşteri Ekle");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 130, 34));

        GeriGel.setBackground(new java.awt.Color(255, 153, 153));
        GeriGel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        GeriGel.setText("BACK");
        GeriGel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriGelActionPerformed(evt);
            }
        });
        getContentPane().add(GeriGel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Ekle.setBackground(new java.awt.Color(255, 153, 153));
        Ekle.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Ekle.setText("Ekle");
        Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleActionPerformed(evt);
            }
        });
        getContentPane().add(Ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 103, 42));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setText("Yaş");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, 30));

        yas_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(yas_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 30));

        jLabel7.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel7.setText("Oda No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, 35));

        hata.setOpaque(true);
        getContentPane().add(hata, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 255, 30));

        gun_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        gun_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gun_alaniActionPerformed(evt);
            }
        });
        getContentPane().add(gun_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 200, 30));

        jLabel8.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel8.setText("Gün sayısı");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 70, 35));

        oda_alani.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        oda_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oda_alaniActionPerformed(evt);
            }
        });
        getContentPane().add(oda_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeriGelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriGelActionPerformed
        RezPage rezPage = new RezPage();
        rezPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GeriGelActionPerformed
    public void odalari_yukle(){
        bos_odalar.forEach((oda) -> {
            oda_alani.addItem(oda);
        });
        
    }
    
    private void EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleActionPerformed
         MusteriEkle musteriEkle = new MusteriEkle(bos_odalar);
         String isim = isim_alani.getText();
         String Soyisim = soyisim_alani.getText();
         int Tc = Integer.parseInt(tc_alani.getText());
         int TelNo = Integer.parseInt(telno_alani.getText());
         int yas = Integer.parseInt(yas_alani.getText());
         int odaNo = Integer.parseInt(oda_alani.getSelectedItem().toString());
         int gun_sayisi = Integer.parseInt(gun_alani.getText());
         
         String query = "INSERT INTO musteriler (ad, soyad, yas, tc, tel_no, oda_no, gun_sayisi, bakiye) VALUES(" +"'" + isim +"'," +"'" +Soyisim +"'," +yas +"," + Tc +
               ","  +TelNo +"," +odaNo +"," +gun_sayisi +"," + 0 +")"  ;
         System.out.println(query);
         
         String query1 = "Update odalar Set kalanlar = " +"'" +isim +"'" +"where oda_no = " +odaNo ;
         System.out.println(query1);
    switch (odaNo) {
        case 1: 
        case 2:
            {
                String query2 = "Update musteriler Set bakiye =" +gun_sayisi*500 + " where oda_no = " +odaNo;
                musteriEkle.ekle(query, query1, query2);
                break;
            }
        case 3:
        case 4:
        case 5:
        case 6:
            {
                String query2 = "Update musteriler Set bakiye =" +gun_sayisi*100 + " where oda_no = " +odaNo;
                musteriEkle.ekle(query, query1, query2);
                break;
            }
        case 8:
        case 7:
            {
                String query2 = "Update musteriler Set bakiye = " +gun_sayisi*250 + " where oda_no =" +odaNo;
                System.out.println(query2);
                musteriEkle.ekle(query, query1, query2);
                break;
            }
        default:
            {
                String query2 = "Update musteriler Set bakiye  =" +gun_sayisi*350 + " where oda_no =" +odaNo ;
                musteriEkle.ekle(query, query1, query2);
                break;
            }
    }
         
         
         
         
         
          
    }//GEN-LAST:event_EkleActionPerformed
    public void ekle(String query, String query1, String query2){
    try {
        statement = (Statement) connection.createStatement();
        statement.executeUpdate(query);
        statement.executeUpdate(query1);
        statement.executeUpdate(query2);
        
    } catch (SQLException ex) {
        Logger.getLogger(MusteriEkle.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
    private void isim_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isim_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isim_alaniActionPerformed

    private void telno_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telno_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telno_alaniActionPerformed

    private void gun_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gun_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gun_alaniActionPerformed

    private void oda_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oda_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oda_alaniActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ekle;
    private javax.swing.JButton GeriGel;
    private javax.swing.JTextField gun_alani;
    private javax.swing.JLabel hata;
    private javax.swing.JTextField isim_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> oda_alani;
    private javax.swing.JTextField soyisim_alani;
    private javax.swing.JTextField tc_alani;
    private javax.swing.JTextField telno_alani;
    private javax.swing.JTextField yas_alani;
    // End of variables declaration//GEN-END:variables

    private void VALUES(String im, String Soyisim, int yas, int Tc, int TelNo, int odaNo, int gun_sayisi, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
