/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donem_proje;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class OtelTest extends javax.swing.JFrame {

    /**
     * Creates new form OtelTest
     */
    public OtelTest() {
        initComponents();
        
        Database db = new Database();
    }
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        Rezervasyon = new javax.swing.JButton();
        MusList = new javax.swing.JButton();
        OdaListele = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 56, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Rezervasyon.setBackground(new java.awt.Color(255, 153, 153));
        Rezervasyon.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Rezervasyon.setForeground(new java.awt.Color(255, 255, 255));
        Rezervasyon.setText("Rezervasyon YAP");
        Rezervasyon.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Rezervasyon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RezervasyonActionPerformed(evt);
            }
        });
        jPanel1.add(Rezervasyon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 250, 75));

        MusList.setBackground(new java.awt.Color(255, 153, 153));
        MusList.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        MusList.setForeground(new java.awt.Color(255, 255, 255));
        MusList.setText("Müşteri Listesi");
        MusList.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        MusList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusListActionPerformed(evt);
            }
        });
        jPanel1.add(MusList, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 75));

        OdaListele.setBackground(new java.awt.Color(255, 153, 153));
        OdaListele.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        OdaListele.setForeground(new java.awt.Color(255, 255, 255));
        OdaListele.setText("Odalları Listele");
        OdaListele.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        OdaListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdaListeleActionPerformed(evt);
            }
        });
        jPanel1.add(OdaListele, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 250, 75));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Çıkış İşlemleri");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 250, 75));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sipariş işlemleri");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 250, 75));

        jLabel1.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OTEL PANAROMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 350, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OdaListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdaListeleActionPerformed
        OdaListesi oda_listesi = new OdaListesi();
        oda_listesi.setVisible(true);
        this.setVisible(false);
          
    }//GEN-LAST:event_OdaListeleActionPerformed

    private void RezervasyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RezervasyonActionPerformed
        RezPage rezPage = new RezPage();
        rezPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RezervasyonActionPerformed

    private void MusListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusListActionPerformed
        MusList musList = new MusList();
        musList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cıkıs cikis = new Cıkıs();
        cikis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtelTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OtelTest().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MusList;
    private javax.swing.JButton OdaListele;
    private javax.swing.JButton Rezervasyon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
