/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donem_proje;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class RezPage extends javax.swing.JFrame {

 Database db;
    Connection connection;
    Statement statement = null;
    public RezPage() {
        initComponents();
        db = new Database();
        connection = (Connection) db.getConnection();
        yükle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oda_tablo = new javax.swing.JTable();
        MusEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 40));

        oda_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Oda NO", "Tür", "Kalan"
            }
        ));
        jScrollPane1.setViewportView(oda_tablo);
        if (oda_tablo.getColumnModel().getColumnCount() > 0) {
            oda_tablo.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 640, 400));

        MusEkle.setBackground(new java.awt.Color(255, 153, 153));
        MusEkle.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        MusEkle.setText("Musteri Ekle");
        MusEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusEkleActionPerformed(evt);
            }
        });
        getContentPane().add(MusEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OtelTest otelTest = new OtelTest();
        otelTest.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MusEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusEkleActionPerformed
        ArrayList<String> bos_odalar = new ArrayList();
        
         try {
            String query = "SELECT oda_no FROM `odalar` WHERE kalanlar IS NULL" ;
            statement = (Statement) connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            
             while (rs.next()) {
               bos_odalar.add(rs.getInt("oda_no")+"");
            }
                                  
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MusList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        MusteriEkle musEkle = new  MusteriEkle(bos_odalar);
        musEkle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MusEkleActionPerformed
    public void yükle() {
                DefaultTableModel tablo = (DefaultTableModel) oda_tablo.getModel();
        try {
            String query = "SELECT * FROM odalar";
            statement = (Statement) connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            System.out.println(query);

            while (rs.next()) {
                Oda oda = new Oda(rs.getInt("oda_no"), rs.getString("oda_turu"), rs.getString("kalanlar"));
                System.out.println(oda);
                tablo.addRow(new Object[]{oda.getOda_no(), oda.getOda_turu(), oda.getKalanlar()});
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(RezPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MusEkle;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable oda_tablo;
    // End of variables declaration//GEN-END:variables
}
